#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    i3-msg exec nm-connection-editor
    exit 1
fi

INTERFACE="${BLOCK_INSTANCE:-wlp9s0}"

state () {
  cat /sys/class/net/$INTERFACE/operstate
}

speed () {
  cat /sys/class/net/$INTERFACE/speed 2> /dev/null
}

ipv4 () {
  ip addr show $INTERFACE | perl -n -e '/inet ([^\/]+)/ && print $1'
}

ssid () {
    iw dev wlp9s0 link | grep SSID | cut -d " " -f 2-
}

strength () {
    grep $INTERFACE /proc/net/wireless | awk '{ print int($3) }'
}

if [ "$(state)" != 'up' ]; then
  echo down # full text
  exit 0
fi

echo "$(ssid) ($(strength)%)"
echo "$(ssid) ($(strength)%)"

# short text
if [ "$(strength)" -gt "50" ]; then
    echo "#36D117"
else
    echo "#d15517"
fi
